---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgADFldasHBpYPbcq0jvZLDP/3ud6tCPgmGUh2MxZ30nM1189GTYzQ/P2eOSeiU4fiUhYL/MocVait++p7AbbhK4qEIeIf69MyS45yv3GgDIMYhNaymD+1L7KQJSfZ2wyK3koSlPQVOfP3D843jSS1tHFX3tSpuOlu6DTGtYwT9rH3xusLeRwIefhdUp95C4vyrhpF4GO7zSchnZzmdLi/hU4s+JV360J4EIJSGFMuB46nGPGztJgZZgvRp+4JCOb1O9gKnwkJdSSPjrWhVNxpHX00Unz+5jgJwQRFWkA5SDl0z4LwmkNOk54I9IigChd+gRjn2PTTiNbTvrV2r/cxMp8kfnrkB0H3wUsIJrhKV1JLJe1Diop1hF7d/m273fwsZOXgCCvF9Tt4f2SFulF1d5pHJkAwn+F2pSFg3FpdbvC3d+P3KG9iImlVgx2+8fKpWIS+BUk+LgQVL8l44vJmMhUtF/dXLWoXthGcK/K8jopnnx3R6y7WX2Ayk638FMwicTWbhIW1f2rYxkHiiQ1fZiEyVihlMbwUBhAMj6nhSESomwnzGW40xIj0NFQcfQFQ+u2SAet0qCyHXjxArfq9aZGat1V1UdendJ3iwFLVawY4dTe8PczvgQ8pZ2wm6MyWtb1hTgaiQ0ir1l6PWehKK/2yiAOzWNp22AdGnBJc4y/yBQFBaRnR4vBs5R96StopPtsrmzNm2aQszO9A==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: staging
