apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: demo.dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-demo-service
            port:
              number: 80
