apiVersion: v1
kind: Service
metadata:
  name: probe-agent
  namespace: monitoring
  labels:
    app: probe-agent
spec:
  selector:
    app: probe-agent
  ports:
  - name: metrics
    port: 19100
    targetPort: 19100
