apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: demo
        env:
        - name: ENV
          value: "dev"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
